# basic golang image
FROM golang:1.24.8-alpine3.21
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk update && \
    apk add --no-cache \
        build-base \  
        curl \
        tcpdump \
        ca-certificates \
        openssl-dev \
        linux-headers \ 
        tzdata && \
    rm -rf /var/cache/apk/*

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN go clean -modcache