// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ai/asr.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "yunyez/internal/pkg/types/pb/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamingRecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*StreamingRecognizeRequest_Config
	//	*StreamingRecognizeRequest_AudioContent
	Request       isStreamingRecognizeRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeRequest) Reset() {
	*x = StreamingRecognizeRequest{}
	mi := &file_ai_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeRequest) ProtoMessage() {}

func (x *StreamingRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeRequest.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_ai_asr_proto_rawDescGZIP(), []int{0}
}

func (x *StreamingRecognizeRequest) GetRequest() isStreamingRecognizeRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamingRecognizeRequest) GetConfig() *StreamingRecognizeConfig {
	if x != nil {
		if x, ok := x.Request.(*StreamingRecognizeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *StreamingRecognizeRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.Request.(*StreamingRecognizeRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

type isStreamingRecognizeRequest_Request interface {
	isStreamingRecognizeRequest_Request()
}

type StreamingRecognizeRequest_Config struct {
	Config *StreamingRecognizeConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"` // 配置信息（首包）
}

type StreamingRecognizeRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"` // 音频数据（后续包）
}

func (*StreamingRecognizeRequest_Config) isStreamingRecognizeRequest_Request() {}

func (*StreamingRecognizeRequest_AudioContent) isStreamingRecognizeRequest_Request() {}

type StreamingRecognizeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoding      string                 `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`                             // 音频编码：LINEAR16_PCM, OPUS, AAC
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`      // 采样率：8000, 16000, 44100, 48000
	NumChannels   int32                  `protobuf:"varint,3,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"`   // 声道数：1=单声道，2=立体声
	LanguageCode  string                 `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"` // 语言：zh-CN, en-US
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeConfig) Reset() {
	*x = StreamingRecognizeConfig{}
	mi := &file_ai_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeConfig) ProtoMessage() {}

func (x *StreamingRecognizeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeConfig.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeConfig) Descriptor() ([]byte, []int) {
	return file_ai_asr_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingRecognizeConfig) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *StreamingRecognizeConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *StreamingRecognizeConfig) GetNumChannels() int32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *StreamingRecognizeConfig) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

type StreamingRecognizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StreamingRecognizeResponse_RecognitionResult
	//	*StreamingRecognizeResponse_Error
	Result        isStreamingRecognizeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeResponse) Reset() {
	*x = StreamingRecognizeResponse{}
	mi := &file_ai_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeResponse) ProtoMessage() {}

func (x *StreamingRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeResponse.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_ai_asr_proto_rawDescGZIP(), []int{2}
}

func (x *StreamingRecognizeResponse) GetResult() isStreamingRecognizeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StreamingRecognizeResponse) GetRecognitionResult() *StreamingRecognitionResult {
	if x != nil {
		if x, ok := x.Result.(*StreamingRecognizeResponse_RecognitionResult); ok {
			return x.RecognitionResult
		}
	}
	return nil
}

func (x *StreamingRecognizeResponse) GetError() *common.Error {
	if x != nil {
		if x, ok := x.Result.(*StreamingRecognizeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingRecognizeResponse_Result interface {
	isStreamingRecognizeResponse_Result()
}

type StreamingRecognizeResponse_RecognitionResult struct {
	RecognitionResult *StreamingRecognitionResult `protobuf:"bytes,1,opt,name=recognition_result,json=recognitionResult,proto3,oneof"` // 识别结果
}

type StreamingRecognizeResponse_Error struct {
	Error *common.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // 错误信息
}

func (*StreamingRecognizeResponse_RecognitionResult) isStreamingRecognizeResponse_Result() {}

func (*StreamingRecognizeResponse_Error) isStreamingRecognizeResponse_Result() {}

type StreamingRecognitionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`           // 识别文本
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`         // 置信度 (0-1)
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // 是否为最终结果
	Stability     float32                `protobuf:"fixed32,4,opt,name=stability,proto3" json:"stability,omitempty"`           // 稳定性 (0-1)，仅中间结果有效
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognitionResult) Reset() {
	*x = StreamingRecognitionResult{}
	mi := &file_ai_asr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognitionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognitionResult) ProtoMessage() {}

func (x *StreamingRecognitionResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_asr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognitionResult.ProtoReflect.Descriptor instead.
func (*StreamingRecognitionResult) Descriptor() ([]byte, []int) {
	return file_ai_asr_proto_rawDescGZIP(), []int{3}
}

func (x *StreamingRecognitionResult) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *StreamingRecognitionResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *StreamingRecognitionResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamingRecognitionResult) GetStability() float32 {
	if x != nil {
		return x.Stability
	}
	return 0
}

type RecognizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioContent  []byte                 `protobuf:"bytes,1,opt,name=audio_content,json=audioContent,proto3" json:"audio_content,omitempty"` // 音频数据（完整）
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`                             // 音频编码
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`      // 采样率
	NumChannels   int32                  `protobuf:"varint,4,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"`   // 声道数
	LanguageCode  string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"` // 语言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_ai_asr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_asr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_ai_asr_proto_rawDescGZIP(), []int{4}
}

func (x *RecognizeRequest) GetAudioContent() []byte {
	if x != nil {
		return x.AudioContent
	}
	return nil
}

func (x *RecognizeRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *RecognizeRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *RecognizeRequest) GetNumChannels() int32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *RecognizeRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

type RecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`   // 识别文本
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 置信度
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`             // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_ai_asr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_asr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_ai_asr_proto_rawDescGZIP(), []int{5}
}

func (x *RecognizeResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *RecognizeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RecognizeResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_ai_asr_proto protoreflect.FileDescriptor

const file_ai_asr_proto_rawDesc = "" +
	"\n" +
	"\fai/asr.proto\x12\x02ai\x1a\x12common/types.proto\"\x85\x01\n" +
	"\x19StreamingRecognizeRequest\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.ai.StreamingRecognizeConfigH\x00R\x06config\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContentB\t\n" +
	"\arequest\"\x9f\x01\n" +
	"\x18StreamingRecognizeConfig\x12\x1a\n" +
	"\bencoding\x18\x01 \x01(\tR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12!\n" +
	"\fnum_channels\x18\x03 \x01(\x05R\vnumChannels\x12#\n" +
	"\rlanguage_code\x18\x04 \x01(\tR\flanguageCode\"\x9e\x01\n" +
	"\x1aStreamingRecognizeResponse\x12O\n" +
	"\x12recognition_result\x18\x01 \x01(\v2\x1e.ai.StreamingRecognitionResultH\x00R\x11recognitionResult\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x95\x01\n" +
	"\x1aStreamingRecognitionResult\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x1c\n" +
	"\tstability\x18\x04 \x01(\x02R\tstability\"\xbc\x01\n" +
	"\x10RecognizeRequest\x12#\n" +
	"\raudio_content\x18\x01 \x01(\fR\faudioContent\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12!\n" +
	"\fnum_channels\x18\x04 \x01(\x05R\vnumChannels\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\"x\n" +
	"\x11RecognizeResponse\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error2\xd8\x01\n" +
	"\n" +
	"ASRService\x12W\n" +
	"\x12StreamingRecognize\x12\x1d.ai.StreamingRecognizeRequest\x1a\x1e.ai.StreamingRecognizeResponse(\x010\x01\x128\n" +
	"\tRecognize\x12\x14.ai.RecognizeRequest\x1a\x15.ai.RecognizeResponse\x127\n" +
	"\x06Health\x12\x15.common.HealthRequest\x1a\x16.common.HealthResponseB!Z\x1fyunyez/internal/pkg/types/pb/aib\x06proto3"

var (
	file_ai_asr_proto_rawDescOnce sync.Once
	file_ai_asr_proto_rawDescData []byte
)

func file_ai_asr_proto_rawDescGZIP() []byte {
	file_ai_asr_proto_rawDescOnce.Do(func() {
		file_ai_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_asr_proto_rawDesc), len(file_ai_asr_proto_rawDesc)))
	})
	return file_ai_asr_proto_rawDescData
}

var file_ai_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ai_asr_proto_goTypes = []any{
	(*StreamingRecognizeRequest)(nil),  // 0: ai.StreamingRecognizeRequest
	(*StreamingRecognizeConfig)(nil),   // 1: ai.StreamingRecognizeConfig
	(*StreamingRecognizeResponse)(nil), // 2: ai.StreamingRecognizeResponse
	(*StreamingRecognitionResult)(nil), // 3: ai.StreamingRecognitionResult
	(*RecognizeRequest)(nil),           // 4: ai.RecognizeRequest
	(*RecognizeResponse)(nil),          // 5: ai.RecognizeResponse
	(*common.Error)(nil),               // 6: common.Error
	(*common.HealthRequest)(nil),       // 7: common.HealthRequest
	(*common.HealthResponse)(nil),      // 8: common.HealthResponse
}
var file_ai_asr_proto_depIdxs = []int32{
	1, // 0: ai.StreamingRecognizeRequest.config:type_name -> ai.StreamingRecognizeConfig
	3, // 1: ai.StreamingRecognizeResponse.recognition_result:type_name -> ai.StreamingRecognitionResult
	6, // 2: ai.StreamingRecognizeResponse.error:type_name -> common.Error
	6, // 3: ai.RecognizeResponse.error:type_name -> common.Error
	0, // 4: ai.ASRService.StreamingRecognize:input_type -> ai.StreamingRecognizeRequest
	4, // 5: ai.ASRService.Recognize:input_type -> ai.RecognizeRequest
	7, // 6: ai.ASRService.Health:input_type -> common.HealthRequest
	2, // 7: ai.ASRService.StreamingRecognize:output_type -> ai.StreamingRecognizeResponse
	5, // 8: ai.ASRService.Recognize:output_type -> ai.RecognizeResponse
	8, // 9: ai.ASRService.Health:output_type -> common.HealthResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_asr_proto_init() }
func file_ai_asr_proto_init() {
	if File_ai_asr_proto != nil {
		return
	}
	file_ai_asr_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamingRecognizeRequest_Config)(nil),
		(*StreamingRecognizeRequest_AudioContent)(nil),
	}
	file_ai_asr_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamingRecognizeResponse_RecognitionResult)(nil),
		(*StreamingRecognizeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_asr_proto_rawDesc), len(file_ai_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_asr_proto_goTypes,
		DependencyIndexes: file_ai_asr_proto_depIdxs,
		MessageInfos:      file_ai_asr_proto_msgTypes,
	}.Build()
	File_ai_asr_proto = out.File
	file_ai_asr_proto_goTypes = nil
	file_ai_asr_proto_depIdxs = nil
}
