// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: ai/asr.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "yunyez/internal/pkg/types/pb/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ASRService_StreamingRecognize_FullMethodName = "/ai.ASRService/StreamingRecognize"
	ASRService_Recognize_FullMethodName          = "/ai.ASRService/Recognize"
	ASRService_Health_FullMethodName             = "/ai.ASRService/Health"
)

// ASRServiceClient is the client API for ASRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ASR 语音识别服务
type ASRServiceClient interface {
	// 流式语音识别（推荐用于实时场景）
	StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingRecognizeRequest, StreamingRecognizeResponse], error)
	// 单次语音识别
	Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	// 健康检查
	Health(ctx context.Context, in *common.HealthRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type aSRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewASRServiceClient(cc grpc.ClientConnInterface) ASRServiceClient {
	return &aSRServiceClient{cc}
}

func (c *aSRServiceClient) StreamingRecognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamingRecognizeRequest, StreamingRecognizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ASRService_ServiceDesc.Streams[0], ASRService_StreamingRecognize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamingRecognizeRequest, StreamingRecognizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASRService_StreamingRecognizeClient = grpc.BidiStreamingClient[StreamingRecognizeRequest, StreamingRecognizeResponse]

func (c *aSRServiceClient) Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, ASRService_Recognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aSRServiceClient) Health(ctx context.Context, in *common.HealthRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, ASRService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ASRServiceServer is the server API for ASRService service.
// All implementations must embed UnimplementedASRServiceServer
// for forward compatibility.
//
// ASR 语音识别服务
type ASRServiceServer interface {
	// 流式语音识别（推荐用于实时场景）
	StreamingRecognize(grpc.BidiStreamingServer[StreamingRecognizeRequest, StreamingRecognizeResponse]) error
	// 单次语音识别
	Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error)
	// 健康检查
	Health(context.Context, *common.HealthRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedASRServiceServer()
}

// UnimplementedASRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedASRServiceServer struct{}

func (UnimplementedASRServiceServer) StreamingRecognize(grpc.BidiStreamingServer[StreamingRecognizeRequest, StreamingRecognizeResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamingRecognize not implemented")
}
func (UnimplementedASRServiceServer) Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedASRServiceServer) Health(context.Context, *common.HealthRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedASRServiceServer) mustEmbedUnimplementedASRServiceServer() {}
func (UnimplementedASRServiceServer) testEmbeddedByValue()                    {}

// UnsafeASRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ASRServiceServer will
// result in compilation errors.
type UnsafeASRServiceServer interface {
	mustEmbedUnimplementedASRServiceServer()
}

func RegisterASRServiceServer(s grpc.ServiceRegistrar, srv ASRServiceServer) {
	// If the following call panics, it indicates UnimplementedASRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ASRService_ServiceDesc, srv)
}

func _ASRService_StreamingRecognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ASRServiceServer).StreamingRecognize(&grpc.GenericServerStream[StreamingRecognizeRequest, StreamingRecognizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASRService_StreamingRecognizeServer = grpc.BidiStreamingServer[StreamingRecognizeRequest, StreamingRecognizeResponse]

func _ASRService_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASRServiceServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASRService_Recognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASRServiceServer).Recognize(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ASRService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ASRServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ASRService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ASRServiceServer).Health(ctx, req.(*common.HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ASRService_ServiceDesc is the grpc.ServiceDesc for ASRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ASRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.ASRService",
	HandlerType: (*ASRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _ASRService_Recognize_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ASRService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingRecognize",
			Handler:       _ASRService_StreamingRecognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ai/asr.proto",
}
