// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ai/nlu.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "yunyez/internal/pkg/types/pb/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 输入文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ai_nlu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_nlu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ai_nlu_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                             // 输入文本
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`                         // 意图
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`               // 置信度
	IsCommand     bool                   `protobuf:"varint,4,opt,name=is_command,json=isCommand,proto3" json:"is_command,omitempty"` // 是否为命令意图
	Error         *common.Error          `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                           // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_ai_nlu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_nlu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_ai_nlu_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PredictResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *PredictResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetIsCommand() bool {
	if x != nil {
		return x.IsCommand
	}
	return false
}

func (x *PredictResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type EmotionJudgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 输入文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionJudgeRequest) Reset() {
	*x = EmotionJudgeRequest{}
	mi := &file_ai_nlu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionJudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionJudgeRequest) ProtoMessage() {}

func (x *EmotionJudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_nlu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionJudgeRequest.ProtoReflect.Descriptor instead.
func (*EmotionJudgeRequest) Descriptor() ([]byte, []int) {
	return file_ai_nlu_proto_rawDescGZIP(), []int{2}
}

func (x *EmotionJudgeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmotionJudgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`               // 输入文本
	Emotion       string                 `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion,omitempty"`         // 情感类型
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 置信度
	Error         *common.Error          `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`             // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionJudgeResponse) Reset() {
	*x = EmotionJudgeResponse{}
	mi := &file_ai_nlu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionJudgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionJudgeResponse) ProtoMessage() {}

func (x *EmotionJudgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_nlu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionJudgeResponse.ProtoReflect.Descriptor instead.
func (*EmotionJudgeResponse) Descriptor() ([]byte, []int) {
	return file_ai_nlu_proto_rawDescGZIP(), []int{3}
}

func (x *EmotionJudgeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmotionJudgeResponse) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *EmotionJudgeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EmotionJudgeResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_ai_nlu_proto protoreflect.FileDescriptor

const file_ai_nlu_proto_rawDesc = "" +
	"\n" +
	"\fai/nlu.proto\x12\x02ai\x1a\x12common/types.proto\"$\n" +
	"\x0ePredictRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xa1\x01\n" +
	"\x0fPredictResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"is_command\x18\x04 \x01(\bR\tisCommand\x12#\n" +
	"\x05error\x18\x05 \x01(\v2\r.common.ErrorR\x05error\")\n" +
	"\x13EmotionJudgeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x89\x01\n" +
	"\x14EmotionJudgeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\aemotion\x18\x02 \x01(\tR\aemotion\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\x05error\x18\x04 \x01(\v2\r.common.ErrorR\x05error2\xbc\x01\n" +
	"\n" +
	"NLUService\x122\n" +
	"\aPredict\x12\x12.ai.PredictRequest\x1a\x13.ai.PredictResponse\x12A\n" +
	"\fEmotionJudge\x12\x17.ai.EmotionJudgeRequest\x1a\x18.ai.EmotionJudgeResponse\x127\n" +
	"\x06Health\x12\x15.common.HealthRequest\x1a\x16.common.HealthResponseB!Z\x1fyunyez/internal/pkg/types/pb/aib\x06proto3"

var (
	file_ai_nlu_proto_rawDescOnce sync.Once
	file_ai_nlu_proto_rawDescData []byte
)

func file_ai_nlu_proto_rawDescGZIP() []byte {
	file_ai_nlu_proto_rawDescOnce.Do(func() {
		file_ai_nlu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_nlu_proto_rawDesc), len(file_ai_nlu_proto_rawDesc)))
	})
	return file_ai_nlu_proto_rawDescData
}

var file_ai_nlu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_nlu_proto_goTypes = []any{
	(*PredictRequest)(nil),        // 0: ai.PredictRequest
	(*PredictResponse)(nil),       // 1: ai.PredictResponse
	(*EmotionJudgeRequest)(nil),   // 2: ai.EmotionJudgeRequest
	(*EmotionJudgeResponse)(nil),  // 3: ai.EmotionJudgeResponse
	(*common.Error)(nil),          // 4: common.Error
	(*common.HealthRequest)(nil),  // 5: common.HealthRequest
	(*common.HealthResponse)(nil), // 6: common.HealthResponse
}
var file_ai_nlu_proto_depIdxs = []int32{
	4, // 0: ai.PredictResponse.error:type_name -> common.Error
	4, // 1: ai.EmotionJudgeResponse.error:type_name -> common.Error
	0, // 2: ai.NLUService.Predict:input_type -> ai.PredictRequest
	2, // 3: ai.NLUService.EmotionJudge:input_type -> ai.EmotionJudgeRequest
	5, // 4: ai.NLUService.Health:input_type -> common.HealthRequest
	1, // 5: ai.NLUService.Predict:output_type -> ai.PredictResponse
	3, // 6: ai.NLUService.EmotionJudge:output_type -> ai.EmotionJudgeResponse
	6, // 7: ai.NLUService.Health:output_type -> common.HealthResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_nlu_proto_init() }
func file_ai_nlu_proto_init() {
	if File_ai_nlu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_nlu_proto_rawDesc), len(file_ai_nlu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_nlu_proto_goTypes,
		DependencyIndexes: file_ai_nlu_proto_depIdxs,
		MessageInfos:      file_ai_nlu_proto_msgTypes,
	}.Build()
	File_ai_nlu_proto = out.File
	file_ai_nlu_proto_goTypes = nil
	file_ai_nlu_proto_depIdxs = nil
}
