// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: ai/nlu.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "yunyez/internal/pkg/types/pb/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NLUService_Predict_FullMethodName      = "/ai.NLUService/Predict"
	NLUService_EmotionJudge_FullMethodName = "/ai.NLUService/EmotionJudge"
	NLUService_Health_FullMethodName       = "/ai.NLUService/Health"
)

// NLUServiceClient is the client API for NLUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NLU 意图识别服务
type NLUServiceClient interface {
	// 意图识别
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// 情感识别
	EmotionJudge(ctx context.Context, in *EmotionJudgeRequest, opts ...grpc.CallOption) (*EmotionJudgeResponse, error)
	// 健康检查
	Health(ctx context.Context, in *common.HealthRequest, opts ...grpc.CallOption) (*common.HealthResponse, error)
}

type nLUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNLUServiceClient(cc grpc.ClientConnInterface) NLUServiceClient {
	return &nLUServiceClient{cc}
}

func (c *nLUServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, NLUService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLUServiceClient) EmotionJudge(ctx context.Context, in *EmotionJudgeRequest, opts ...grpc.CallOption) (*EmotionJudgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionJudgeResponse)
	err := c.cc.Invoke(ctx, NLUService_EmotionJudge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLUServiceClient) Health(ctx context.Context, in *common.HealthRequest, opts ...grpc.CallOption) (*common.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthResponse)
	err := c.cc.Invoke(ctx, NLUService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NLUServiceServer is the server API for NLUService service.
// All implementations must embed UnimplementedNLUServiceServer
// for forward compatibility.
//
// NLU 意图识别服务
type NLUServiceServer interface {
	// 意图识别
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// 情感识别
	EmotionJudge(context.Context, *EmotionJudgeRequest) (*EmotionJudgeResponse, error)
	// 健康检查
	Health(context.Context, *common.HealthRequest) (*common.HealthResponse, error)
	mustEmbedUnimplementedNLUServiceServer()
}

// UnimplementedNLUServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNLUServiceServer struct{}

func (UnimplementedNLUServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedNLUServiceServer) EmotionJudge(context.Context, *EmotionJudgeRequest) (*EmotionJudgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmotionJudge not implemented")
}
func (UnimplementedNLUServiceServer) Health(context.Context, *common.HealthRequest) (*common.HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNLUServiceServer) mustEmbedUnimplementedNLUServiceServer() {}
func (UnimplementedNLUServiceServer) testEmbeddedByValue()                    {}

// UnsafeNLUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NLUServiceServer will
// result in compilation errors.
type UnsafeNLUServiceServer interface {
	mustEmbedUnimplementedNLUServiceServer()
}

func RegisterNLUServiceServer(s grpc.ServiceRegistrar, srv NLUServiceServer) {
	// If the following call panics, it indicates UnimplementedNLUServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NLUService_ServiceDesc, srv)
}

func _NLUService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLUServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLUService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLUServiceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLUService_EmotionJudge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmotionJudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLUServiceServer).EmotionJudge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLUService_EmotionJudge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLUServiceServer).EmotionJudge(ctx, req.(*EmotionJudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLUService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLUServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLUService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLUServiceServer).Health(ctx, req.(*common.HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NLUService_ServiceDesc is the grpc.ServiceDesc for NLUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NLUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.NLUService",
	HandlerType: (*NLUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _NLUService_Predict_Handler,
		},
		{
			MethodName: "EmotionJudge",
			Handler:    _NLUService_EmotionJudge_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NLUService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/nlu.proto",
}
