// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ai/tts.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "yunyez/internal/pkg/types/pb/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamingSynthesizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*StreamingSynthesizeRequest_Config
	//	*StreamingSynthesizeRequest_Text
	Request       isStreamingSynthesizeRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingSynthesizeRequest) Reset() {
	*x = StreamingSynthesizeRequest{}
	mi := &file_ai_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingSynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingSynthesizeRequest) ProtoMessage() {}

func (x *StreamingSynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingSynthesizeRequest.ProtoReflect.Descriptor instead.
func (*StreamingSynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_ai_tts_proto_rawDescGZIP(), []int{0}
}

func (x *StreamingSynthesizeRequest) GetRequest() isStreamingSynthesizeRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StreamingSynthesizeRequest) GetConfig() *StreamingSynthesizeConfig {
	if x != nil {
		if x, ok := x.Request.(*StreamingSynthesizeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *StreamingSynthesizeRequest) GetText() string {
	if x != nil {
		if x, ok := x.Request.(*StreamingSynthesizeRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

type isStreamingSynthesizeRequest_Request interface {
	isStreamingSynthesizeRequest_Request()
}

type StreamingSynthesizeRequest_Config struct {
	Config *StreamingSynthesizeConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"` // 配置信息（首包）
}

type StreamingSynthesizeRequest_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"` // 文本内容（后续包，支持分块）
}

func (*StreamingSynthesizeRequest_Config) isStreamingSynthesizeRequest_Request() {}

func (*StreamingSynthesizeRequest_Text) isStreamingSynthesizeRequest_Request() {}

type StreamingSynthesizeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voice         string                 `protobuf:"bytes,1,opt,name=voice,proto3" json:"voice,omitempty"`                                   // 语音：zh-CN-XiaoxiaoNeural, en-US-JennyNeural
	Rate          float32                `protobuf:"fixed32,2,opt,name=rate,proto3" json:"rate,omitempty"`                                   // 语速：0.5-2.0
	Pitch         float32                `protobuf:"fixed32,3,opt,name=pitch,proto3" json:"pitch,omitempty"`                                 // 音调：0.5-2.0
	Volume        float32                `protobuf:"fixed32,4,opt,name=volume,proto3" json:"volume,omitempty"`                               // 音量：0.0-1.0
	OutputFormat  string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // 输出格式：AUDIO_16KHZ_16BIT_RAW_PCM, AUDIO_24KHZ_48KBITRATE_GZIP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingSynthesizeConfig) Reset() {
	*x = StreamingSynthesizeConfig{}
	mi := &file_ai_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingSynthesizeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingSynthesizeConfig) ProtoMessage() {}

func (x *StreamingSynthesizeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingSynthesizeConfig.ProtoReflect.Descriptor instead.
func (*StreamingSynthesizeConfig) Descriptor() ([]byte, []int) {
	return file_ai_tts_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingSynthesizeConfig) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *StreamingSynthesizeConfig) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *StreamingSynthesizeConfig) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *StreamingSynthesizeConfig) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StreamingSynthesizeConfig) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type StreamingSynthesizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StreamingSynthesizeResponse_AudioContent
	//	*StreamingSynthesizeResponse_Error
	Result        isStreamingSynthesizeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingSynthesizeResponse) Reset() {
	*x = StreamingSynthesizeResponse{}
	mi := &file_ai_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingSynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingSynthesizeResponse) ProtoMessage() {}

func (x *StreamingSynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingSynthesizeResponse.ProtoReflect.Descriptor instead.
func (*StreamingSynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_ai_tts_proto_rawDescGZIP(), []int{2}
}

func (x *StreamingSynthesizeResponse) GetResult() isStreamingSynthesizeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StreamingSynthesizeResponse) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.Result.(*StreamingSynthesizeResponse_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

func (x *StreamingSynthesizeResponse) GetError() *common.Error {
	if x != nil {
		if x, ok := x.Result.(*StreamingSynthesizeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamingSynthesizeResponse_Result interface {
	isStreamingSynthesizeResponse_Result()
}

type StreamingSynthesizeResponse_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,1,opt,name=audio_content,json=audioContent,proto3,oneof"` // 音频数据
}

type StreamingSynthesizeResponse_Error struct {
	Error *common.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // 错误信息
}

func (*StreamingSynthesizeResponse_AudioContent) isStreamingSynthesizeResponse_Result() {}

func (*StreamingSynthesizeResponse_Error) isStreamingSynthesizeResponse_Result() {}

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                     // 输入文本
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`                                   // 语音
	Rate          float32                `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`                                   // 语速
	Pitch         float32                `protobuf:"fixed32,4,opt,name=pitch,proto3" json:"pitch,omitempty"`                                 // 音调
	Volume        float32                `protobuf:"fixed32,5,opt,name=volume,proto3" json:"volume,omitempty"`                               // 音量
	OutputFormat  string                 `protobuf:"bytes,6,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // 输出格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_ai_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_ai_tts_proto_rawDescGZIP(), []int{3}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SynthesizeRequest) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *SynthesizeRequest) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *SynthesizeRequest) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SynthesizeRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type SynthesizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioContent  []byte                 `protobuf:"bytes,1,opt,name=audio_content,json=audioContent,proto3" json:"audio_content,omitempty"` // 音频数据
	DurationMs    int32                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`      // 音频时长（毫秒）
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                   // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_ai_tts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_tts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_ai_tts_proto_rawDescGZIP(), []int{4}
}

func (x *SynthesizeResponse) GetAudioContent() []byte {
	if x != nil {
		return x.AudioContent
	}
	return nil
}

func (x *SynthesizeResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SynthesizeResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_ai_tts_proto protoreflect.FileDescriptor

const file_ai_tts_proto_rawDesc = "" +
	"\n" +
	"\fai/tts.proto\x12\x02ai\x1a\x12common/types.proto\"v\n" +
	"\x1aStreamingSynthesizeRequest\x127\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.ai.StreamingSynthesizeConfigH\x00R\x06config\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04textB\t\n" +
	"\arequest\"\x98\x01\n" +
	"\x19StreamingSynthesizeConfig\x12\x14\n" +
	"\x05voice\x18\x01 \x01(\tR\x05voice\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x02R\x04rate\x12\x14\n" +
	"\x05pitch\x18\x03 \x01(\x02R\x05pitch\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x02R\x06volume\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"u\n" +
	"\x1bStreamingSynthesizeResponse\x12%\n" +
	"\raudio_content\x18\x01 \x01(\fH\x00R\faudioContent\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xa4\x01\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x02R\x04rate\x12\x14\n" +
	"\x05pitch\x18\x04 \x01(\x02R\x05pitch\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x02R\x06volume\x12#\n" +
	"\routput_format\x18\x06 \x01(\tR\foutputFormat\"\x7f\n" +
	"\x12SynthesizeResponse\x12#\n" +
	"\raudio_content\x18\x01 \x01(\fR\faudioContent\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x05R\n" +
	"durationMs\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error2\xde\x01\n" +
	"\n" +
	"TTSService\x12Z\n" +
	"\x13StreamingSynthesize\x12\x1e.ai.StreamingSynthesizeRequest\x1a\x1f.ai.StreamingSynthesizeResponse(\x010\x01\x12;\n" +
	"\n" +
	"Synthesize\x12\x15.ai.SynthesizeRequest\x1a\x16.ai.SynthesizeResponse\x127\n" +
	"\x06Health\x12\x15.common.HealthRequest\x1a\x16.common.HealthResponseB!Z\x1fyunyez/internal/pkg/types/pb/aib\x06proto3"

var (
	file_ai_tts_proto_rawDescOnce sync.Once
	file_ai_tts_proto_rawDescData []byte
)

func file_ai_tts_proto_rawDescGZIP() []byte {
	file_ai_tts_proto_rawDescOnce.Do(func() {
		file_ai_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_tts_proto_rawDesc), len(file_ai_tts_proto_rawDesc)))
	})
	return file_ai_tts_proto_rawDescData
}

var file_ai_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_tts_proto_goTypes = []any{
	(*StreamingSynthesizeRequest)(nil),  // 0: ai.StreamingSynthesizeRequest
	(*StreamingSynthesizeConfig)(nil),   // 1: ai.StreamingSynthesizeConfig
	(*StreamingSynthesizeResponse)(nil), // 2: ai.StreamingSynthesizeResponse
	(*SynthesizeRequest)(nil),           // 3: ai.SynthesizeRequest
	(*SynthesizeResponse)(nil),          // 4: ai.SynthesizeResponse
	(*common.Error)(nil),                // 5: common.Error
	(*common.HealthRequest)(nil),        // 6: common.HealthRequest
	(*common.HealthResponse)(nil),       // 7: common.HealthResponse
}
var file_ai_tts_proto_depIdxs = []int32{
	1, // 0: ai.StreamingSynthesizeRequest.config:type_name -> ai.StreamingSynthesizeConfig
	5, // 1: ai.StreamingSynthesizeResponse.error:type_name -> common.Error
	5, // 2: ai.SynthesizeResponse.error:type_name -> common.Error
	0, // 3: ai.TTSService.StreamingSynthesize:input_type -> ai.StreamingSynthesizeRequest
	3, // 4: ai.TTSService.Synthesize:input_type -> ai.SynthesizeRequest
	6, // 5: ai.TTSService.Health:input_type -> common.HealthRequest
	2, // 6: ai.TTSService.StreamingSynthesize:output_type -> ai.StreamingSynthesizeResponse
	4, // 7: ai.TTSService.Synthesize:output_type -> ai.SynthesizeResponse
	7, // 8: ai.TTSService.Health:output_type -> common.HealthResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ai_tts_proto_init() }
func file_ai_tts_proto_init() {
	if File_ai_tts_proto != nil {
		return
	}
	file_ai_tts_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamingSynthesizeRequest_Config)(nil),
		(*StreamingSynthesizeRequest_Text)(nil),
	}
	file_ai_tts_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamingSynthesizeResponse_AudioContent)(nil),
		(*StreamingSynthesizeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_tts_proto_rawDesc), len(file_ai_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_tts_proto_goTypes,
		DependencyIndexes: file_ai_tts_proto_depIdxs,
		MessageInfos:      file_ai_tts_proto_msgTypes,
	}.Build()
	File_ai_tts_proto = out.File
	file_ai_tts_proto_goTypes = nil
	file_ai_tts_proto_depIdxs = nil
}
